"""Rewrites a Fiber node config generated by udt-init for the Docker network.

Usage: patch_node_config.py SRC DST NODE_IP

- P2P listens on 8228 and announces the container's private IP.
- RPC listens on the container's private IP (Fiber refuses public addresses without Biscuit auth).
- The CKB RPC is the chain container.
- Only the fiber, rpc and ckb services run: the cross-chain hub needs LND, which these tests don't use.
"""
import sys

import yaml


class HexPreservingLoader(yaml.SafeLoader):
    """YAML 1.1 reads 0x... scalars as integers, which would turn code hashes and
    tx hashes into decimal numbers when the file is written back. Keep them as strings."""


def _construct_int(loader, node):
    text = loader.construct_scalar(node)
    if text.lower().lstrip("+-").startswith("0x"):
        return text
    return yaml.SafeLoader.construct_yaml_int(loader, node)


HexPreservingLoader.add_constructor("tag:yaml.org,2002:int", _construct_int)

src, dst, ip = sys.argv[1:4]
with open(src) as f:
    cfg = yaml.load(f, Loader=HexPreservingLoader)

cfg["fiber"]["listening_addr"] = "/ip4/0.0.0.0/tcp/8228"
cfg["fiber"]["announced_addrs"] = [f"/ip4/{ip}/tcp/8228"]
cfg["rpc"]["listening_addr"] = f"{ip}:8227"
cfg["rpc"]["enabled_modules"] = [m for m in cfg["rpc"]["enabled_modules"] if m != "cch"]
cfg.setdefault("ckb", {})["rpc_url"] = "http://10.77.0.10:8114"
cfg["services"] = ["fiber", "rpc", "ckb"]
cfg.pop("cch", None)

with open(dst, "w") as f:
    yaml.safe_dump(cfg, f, sort_keys=False)
